name: farmadev
description: "Bienvenidos a Farmadev."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  mysql_client: ^0.0.27
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^0.8.7+3

flutter:
  uses-material-design: true
